### PR TITLE
Use aiohttp instead of requests

### PR DESCRIPTION
**Pull request by Dorikyh**
When you use requests you are making an asynchronous request, that is, the execution flow (that is, the program) will stop completely until the request is successful. Due to the way discord.py is made, asynchronous requests must be used so that the bot does not stop momentarily when making an http request.

Also I created the fetch() function to make easier requests.

I haven't tested if this works, but I'm sure it works because I've programmed this countless times.

### CODE REVIEW

**Comment by realduziy** [comment]
I will look into this soon I just did a lot of updating and added some new features that still need work but the basics are all there now. Thanks for the suggestion; I appreciate it!

**Comment by Dorikyh** [comment]
No problem, anyway I really recommend that you use cogs, they are very necessary to have an organized development environment and be able to avoid future problems. And also be careful with synchronous functions which are a problem for an asynchronous script.

**Comment by realduziy** [comment]
Cogs is on the list of things that I need to do since I started this little project. I'm going to be looking into cogs pretty soon, actually. Everything right now is sort of organized to the point where I know where everything is, but seeing that I'm adding some big features that are really long, I can see how there might be problems down the line with stuff interfering with one another. Also, thanks for the heads-up on the synchronous functions; I will be looking into this as well.

**Comment by realduziy** [comment]
I changed; the way you had it did not work correctly for me, but I ended up getting it to work. None the less, thanks for the advice again.

**Pull request closed without merging**
